logo:
  avatar: '[https://github.com/nian1123.png](/)'
  title: '[念一的博客](/)'
  subtitle: 记录技术、阅读与生活

menubar:
  columns: 4
  items: []

site_tree:
  home:
    leftbar: intro, recent
    rightbar:
  index_blog:
    menu_id: post
    leftbar: intro, recent
    rightbar:
  post:
    menu_id: post
    leftbar: intro, recent
    rightbar: toc
  page:
    leftbar: intro, recent
    rightbar: toc
  error_page:
    menu_id: post
    '404': /404.html
    leftbar: intro, recent
    rightbar:

article:
  type: tech
  auto_excerpt: 160
  license: 本文采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。
  share:
    - link
    - wechat
    - weibo

footer:
  social:
  sitemap: []
  content: |
    本站由 [{author.name}](/) 使用 [{theme.name} {theme.version}]({theme.tree}) 主题创建。
    内容以文章与周刊为主。

search:
  service: local_search
  local_search:
    field: all
    path: /search.json
    content: true

comments:
  service:

inject:
  head:
    - |
      <link rel="icon" type="image/svg+xml" href="/favicon.svg">
      <link rel="apple-touch-icon" href="/favicon.svg">
    - |
      <style>
        .l_body[type='tech'] article.content h2 > a:first-child:before,
        .l_body[type='tech'] article.content h3 > a:first-child:before {
          content: ' ';
        }
      </style>
